# Example terraform-branch-deploy configuration
# Place this file at .tf-branch-deploy.yml in your repository root

# The default environment for commands without explicit target
default-environment: dev

# Environments requiring extra safety checks
production-environments:
  - prod

# The branch containing stable infrastructure state
stable-branch: main

# Environment definitions
environments:
  dev:
    working-directory: ./terraform/environments/dev
    var-files:
      paths:
        - common.tfvars
        - dev.tfvars
    backend-configs:
      paths:
        - backends/dev.tfbackend

  staging:
    working-directory: ./terraform/environments/staging
    var-files:
      paths:
        - common.tfvars
        - staging.tfvars
    backend-configs:
      paths:
        - backends/staging.tfbackend

  prod:
    working-directory: ./terraform/environments/prod
    var-files:
      paths:
        - common.tfvars
        - prod.tfvars
    backend-configs:
      paths:
        - backends/prod.tfbackend
    # Production-specific args
    apply-args:
      args:
        - "-parallelism=5"

# Global defaults inherited by all environments
defaults:
  plan-args:
    args:
      - "-compact-warnings"
  init-args:
    args:
      - "-upgrade"
