name: terraform-branch-deploy
description: ChatOps for Terraform deployments via GitHub PRs - perfect integration with branch-deploy

author: Sourab Kanthavar <@scarowar>

branding:
  icon: git-pull-request
  color: purple

inputs:
  # === TF-BRANCH-DEPLOY SPECIFIC ===
  github-token:
    description: "GitHub token with pull-requests:write, deployments:write, contents:write"
    required: true
  mode:
    description: "skip = just outputs, run = execute terraform"
    default: "run"
  config-path:
    description: "Path to .tf-branch-deploy.yml"
    default: ".tf-branch-deploy.yml"
  terraform-version:
    description: "Terraform version to install"
    default: "latest"

  # === BRANCH-DEPLOY TRIGGERS ===
  trigger:
    description: "Deploy command trigger"
    default: ".apply"
  noop-trigger:
    description: "Plan command trigger"
    default: ".plan"
  lock-trigger:
    description: "Lock command trigger"
    default: ".lock"
  unlock-trigger:
    description: "Unlock command trigger"
    default: ".unlock"
  help-trigger:
    description: "Help command trigger"
    default: ".help"
  lock-info-alias:
    description: "Lock info alias"
    default: ".wcid"
  param-separator:
    description: "Parameter separator in commands"
    default: "|"

  # === BRANCH-DEPLOY ENVIRONMENTS ===
  environment:
    description: "Default environment"
    default: ""
  environment-targets:
    description: "Comma-separated environments (auto-detected from config if empty)"
    default: ""
  production-environments:
    description: "Comma-separated production environments"
    default: ""
  environment-urls:
    description: "Environment URLs mapping"
    default: ""
  draft-permitted-targets:
    description: "Environments allowing draft PR deployments"
    default: ""

  # === BRANCH-DEPLOY BRANCH SAFETY ===
  stable-branch:
    description: "Stable branch for rollbacks"
    default: "main"
  update-branch:
    description: "How to handle outdated branches: disabled|warn|force"
    default: "warn"
  outdated-mode:
    description: "Branch freshness check: strict|pr_base|default_branch"
    default: "strict"
  allow-sha-deployments:
    description: "Allow deploying specific SHAs"
    default: "false"
  enforced-deployment-order:
    description: "Required deployment order (e.g., dev,staging,prod)"
    default: ""

  # === BRANCH-DEPLOY CI/REVIEWS ===
  checks:
    description: "CI check requirements: all|required|<check-names>"
    default: "all"
  ignored-checks:
    description: "Checks to ignore"
    default: ""
  skip-ci:
    description: "Environments that skip CI"
    default: ""
  skip-reviews:
    description: "Environments that skip reviews"
    default: ""
  required-contexts:
    description: "Manually required status contexts"
    default: "false"

  # === BRANCH-DEPLOY SECURITY ===
  permissions:
    description: "Required GitHub permissions"
    default: "write,admin"
  admins:
    description: "Admin users/teams"
    default: "false"
  admins-pat:
    description: "PAT for admin team lookups"
    default: "false"
  commit-verification:
    description: "Require verified commits"
    default: "false"
  disable-naked-commands:
    description: "Require environment in commands"
    default: "true"
  allow-forks:
    description: "Allow fork deployments"
    default: "true"
  allow-non-default-target-branch:
    description: "Allow non-default target branch deployments"
    default: "false"
  deployment-confirmation:
    description: "Require deployment confirmation"
    default: "false"
  deployment-confirmation-timeout:
    description: "Confirmation timeout in seconds"
    default: "60"

  # === BRANCH-DEPLOY LOCKS ===
  global-lock-flag:
    description: "Global lock flag"
    default: "--global"
  sticky-locks:
    description: "Keep locks after deployment"
    default: "false"
  sticky-locks-for-noop:
    description: "Keep locks for plan operations"
    default: "false"

  # === BRANCH-DEPLOY LABELS ===
  successful-deploy-labels:
    description: "Labels for successful deploy"
    default: ""
  successful-noop-labels:
    description: "Labels for successful plan"
    default: ""
  failed-deploy-labels:
    description: "Labels for failed deploy"
    default: ""
  failed-noop-labels:
    description: "Labels for failed plan"
    default: ""
  skip-successful-noop-labels-if-approved:
    description: "Skip noop labels if PR is approved"
    default: "false"
  skip-successful-deploy-labels-if-approved:
    description: "Skip deploy labels if PR is approved"
    default: "false"

  # === BRANCH-DEPLOY ADVANCED ===
  use-security-warnings:
    description: "Show security warnings in logs"
    default: "true"
  merge-deploy-mode:
    description: "Enable merge deploy mode"
    default: "false"
  unlock-on-merge-mode:
    description: "Unlock environments on PR merge"
    default: "false"
  environment-url-in-comment:
    description: "Append environment URL to success comment"
    default: "true"
  skip-completing:
    description: "Skip deployment completion (we handle this)"
    default: "true"
  deploy-message-path:
    description: "Custom deployment message template"
    default: ".github/deployment_message.md"
  reaction:
    description: "Reaction emoji for trigger detection"
    default: "eyes"

outputs:
  # From branch-deploy
  continue:
    description: "'true' if deployment should proceed"
    value: ${{ steps.branch-deploy.outputs.continue }}
  triggered:
    description: "'true' if command was detected"
    value: ${{ steps.branch-deploy.outputs.triggered }}
  environment:
    description: "Target environment"
    value: ${{ steps.branch-deploy.outputs.environment }}
  sha:
    description: "Commit SHA to deploy"
    value: ${{ steps.branch-deploy.outputs.sha }}
  ref:
    description: "Branch ref to deploy"
    value: ${{ steps.branch-deploy.outputs.ref }}
  noop:
    description: "'true' for plan operations"
    value: ${{ steps.branch-deploy.outputs.noop }}
  actor:
    description: "User who triggered deployment"
    value: ${{ steps.branch-deploy.outputs.actor }}
  params:
    description: "Raw parameters from command"
    value: ${{ steps.branch-deploy.outputs.params }}
  comment-id:
    description: "Triggering comment ID"
    value: ${{ steps.branch-deploy.outputs.comment_id }}
  deployment-id:
    description: "GitHub deployment ID"
    value: ${{ steps.branch-deploy.outputs.deployment_id }}
  type:
    description: "Command type (deploy, lock, unlock, etc.)"
    value: ${{ steps.branch-deploy.outputs.type }}

  # Terraform-specific
  working-directory:
    description: "Terraform working directory"
    value: ${{ steps.tf-run.outputs.working_directory }}
  var-files:
    description: "JSON array of var files"
    value: ${{ steps.tf-run.outputs.var_files }}
  backend-configs:
    description: "JSON array of backend config files"
    value: ${{ steps.tf-run.outputs.backend_configs }}
  is-production:
    description: "'true' if production environment"
    value: ${{ steps.tf-run.outputs.is_production }}
  plan-file:
    description: "Path to plan file (after plan)"
    value: ${{ steps.tf-run.outputs.plan_file }}
  plan-checksum:
    description: "SHA256 of plan file"
    value: ${{ steps.tf-run.outputs.plan_checksum }}
  has-changes:
    description: "'true' if plan has changes"
    value: ${{ steps.tf-run.outputs.has_changes }}

runs:
  using: composite
  steps:
    # === SETUP ===
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Setup UV
      uses: astral-sh/setup-uv@v5

    - name: Install tf-branch-deploy
      shell: bash
      run: uv pip install --system "${{ github.action_path }}"

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}
        terraform_wrapper: false

    # === GET ENVIRONMENT TARGETS FROM CONFIG ===
    - name: Detect environments
      id: detect-envs
      shell: bash
      run: |
        if [ -n "${{ inputs.environment-targets }}" ]; then
          echo "targets=${{ inputs.environment-targets }}" >> $GITHUB_OUTPUT
          echo "default=${{ inputs.environment }}" >> $GITHUB_OUTPUT
          echo "production=${{ inputs.production-environments }}" >> $GITHUB_OUTPUT
        else
          config_path="${{ inputs.config-path }}"
          if [ -f "$config_path" ]; then
            targets=$(tf-branch-deploy environments --config "$config_path" 2>/dev/null || echo "production")
            default=$(yq -r '.["default-environment"] // "production"' "$config_path" 2>/dev/null || echo "production")
            production=$(yq -r '.["production-environments"] | join(",")' "$config_path" 2>/dev/null || echo "production")
          else
            targets="production"
            default="production"
            production="production"
          fi
          echo "targets=$targets" >> $GITHUB_OUTPUT
          echo "default=$default" >> $GITHUB_OUTPUT
          echo "production=$production" >> $GITHUB_OUTPUT
        fi

    # === BRANCH-DEPLOY (IssueOps Engine) ===
    - name: IssueOps Command Dispatcher
      id: branch-deploy
      uses: github/branch-deploy@v11
      with:
        github_token: ${{ inputs.github-token }}
        # Triggers
        trigger: ${{ inputs.trigger }}
        noop_trigger: ${{ inputs.noop-trigger }}
        lock_trigger: ${{ inputs.lock-trigger }}
        unlock_trigger: ${{ inputs.unlock-trigger }}
        help_trigger: ${{ inputs.help-trigger }}
        lock_info_alias: ${{ inputs.lock-info-alias }}
        param_separator: ${{ inputs.param-separator }}
        # Environments
        environment: ${{ steps.detect-envs.outputs.default }}
        environment_targets: ${{ steps.detect-envs.outputs.targets }}
        production_environments: ${{ steps.detect-envs.outputs.production }}
        environment_urls: ${{ inputs.environment-urls }}
        draft_permitted_targets: ${{ inputs.draft-permitted-targets }}
        # Branch safety
        stable_branch: ${{ inputs.stable-branch }}
        update_branch: ${{ inputs.update-branch }}
        outdated_mode: ${{ inputs.outdated-mode }}
        allow_sha_deployments: ${{ inputs.allow-sha-deployments }}
        enforced_deployment_order: ${{ inputs.enforced-deployment-order }}
        # CI/Reviews
        checks: ${{ inputs.checks }}
        ignored_checks: ${{ inputs.ignored-checks }}
        skip_ci: ${{ inputs.skip-ci }}
        skip_reviews: ${{ inputs.skip-reviews }}
        required_contexts: ${{ inputs.required-contexts }}
        # Security
        permissions: ${{ inputs.permissions }}
        admins: ${{ inputs.admins }}
        admins_pat: ${{ inputs.admins-pat }}
        commit_verification: ${{ inputs.commit-verification }}
        disable_naked_commands: ${{ inputs.disable-naked-commands }}
        allow_forks: ${{ inputs.allow-forks }}
        allow_non_default_target_branch_deployments: ${{ inputs.allow-non-default-target-branch }}
        deployment_confirmation: ${{ inputs.deployment-confirmation }}
        deployment_confirmation_timeout: ${{ inputs.deployment-confirmation-timeout }}
        # Locks
        global_lock_flag: ${{ inputs.global-lock-flag }}
        sticky_locks: ${{ inputs.sticky-locks }}
        sticky_locks_for_noop: ${{ inputs.sticky-locks-for-noop }}
        # Labels
        successful_deploy_labels: ${{ inputs.successful-deploy-labels }}
        successful_noop_labels: ${{ inputs.successful-noop-labels }}
        failed_deploy_labels: ${{ inputs.failed-deploy-labels }}
        failed_noop_labels: ${{ inputs.failed-noop-labels }}
        # Advanced
        skip_completing: ${{ inputs.skip-completing }}
        deploy_message_path: ${{ inputs.deploy-message-path }}
        reaction: ${{ inputs.reaction }}

    # === TERRAFORM EXECUTION ===
    - name: Execute Terraform
      id: tf-run
      if: steps.branch-deploy.outputs.continue == 'true'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        TF_BD_PR_NUMBER: ${{ steps.branch-deploy.outputs.issue_number }}
      run: |
        operation="${{ steps.branch-deploy.outputs.noop == 'true' && 'plan' || 'apply' }}"
        
        tf-branch-deploy run \
          --environment "${{ steps.branch-deploy.outputs.environment }}" \
          --operation "$operation" \
          --sha "${{ steps.branch-deploy.outputs.sha }}" \
          --config "${{ inputs.config-path }}" \
          --mode "${{ inputs.mode }}"
