sonar.projectKey=scarowar_terraform-branch-deploy
sonar.organization=scarowar
sonar.projectName=terraform-branch-deploy

sonar.sources=src
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8

sonar.exclusions=site/**,dist/**,htmlcov/**,.venv/**,.ruff_cache/**
sonar.coverage.exclusions=tests/**
